In [13]:
import pandas as pd
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

In [14]:
currency = pd.read_excel('C:/Users/lenovo/Desktop/EURUSD.xlsx') #read the excel file

In [15]:
currency

Date    Open    High     Low   Close
0    2022-06-14 12:36:00  1.0420  1.0420  1.0419  1.0419
1    2022-06-14 12:35:00  1.0421  1.0422  1.0419  1.0419
2    2022-06-14 12:34:00  1.0423  1.0423  1.0421  1.0421
3    2022-06-14 12:33:00  1.0422  1.0423  1.0421  1.0423
4    2022-06-14 12:32:00  1.0422  1.0422  1.0420  1.0422
...                  ...     ...     ...     ...     ...
4109 2022-06-09 17:04:00  1.0617  1.0618  1.0617  1.0618
4110 2022-06-09 17:03:00  1.0617  1.0617  1.0617  1.0617
4111 2022-06-09 17:02:00  1.0617  1.0617  1.0617  1.0617
4112 2022-06-09 17:01:00  1.0617  1.0617  1.0616  1.0617
4113 2022-06-09 17:00:00  1.0617  1.0618  1.0617  1.0617

[4114 rows x 5 columns]

In [16]:
# use new column 'return' instead of columns 'Open' and 'Close'

# add new column 'return'
currency['return'] = np.log(currency['Close']) - np.log(currency['Open'])
currency

Date    Open    High     Low   Close    return
0    2022-06-14 12:36:00  1.0420  1.0420  1.0419  1.0419 -0.000096
1    2022-06-14 12:35:00  1.0421  1.0422  1.0419  1.0419 -0.000192
2    2022-06-14 12:34:00  1.0423  1.0423  1.0421  1.0421 -0.000192
3    2022-06-14 12:33:00  1.0422  1.0423  1.0421  1.0423  0.000096
4    2022-06-14 12:32:00  1.0422  1.0422  1.0420  1.0422  0.000000
...                  ...     ...     ...     ...     ...       ...
4109 2022-06-09 17:04:00  1.0617  1.0618  1.0617  1.0618  0.000094
4110 2022-06-09 17:03:00  1.0617  1.0617  1.0617  1.0617  0.000000
4111 2022-06-09 17:02:00  1.0617  1.0617  1.0617  1.0617  0.000000
4112 2022-06-09 17:01:00  1.0617  1.0617  1.0616  1.0617  0.000000
4113 2022-06-09 17:00:00  1.0617  1.0618  1.0617  1.0617  0.000000

[4114 rows x 6 columns]

In [17]:
# delete columns 'Open' and 'Close'
del currency['Open'], currency['Close']
currency

Date    High     Low    return
0    2022-06-14 12:36:00  1.0420  1.0419 -0.000096
1    2022-06-14 12:35:00  1.0422  1.0419 -0.000192
2    2022-06-14 12:34:00  1.0423  1.0421 -0.000192
3    2022-06-14 12:33:00  1.0423  1.0421  0.000096
4    2022-06-14 12:32:00  1.0422  1.0420  0.000000
...                  ...     ...     ...       ...
4109 2022-06-09 17:04:00  1.0618  1.0617  0.000094
4110 2022-06-09 17:03:00  1.0617  1.0617  0.000000
4111 2022-06-09 17:02:00  1.0617  1.0617  0.000000
4112 2022-06-09 17:01:00  1.0617  1.0616  0.000000
4113 2022-06-09 17:00:00  1.0618  1.0617  0.000000

[4114 rows x 4 columns]

In [18]:
# Now I'd like to consider to use the return of last 5 minutes to predict the return of next 1 minute

# Firstly, construct the features and label matrix

In [27]:
cur_r= currency[['Date','return']]
cur_r

Date    return
0    2022-06-14 12:36:00 -0.000096
1    2022-06-14 12:35:00 -0.000192
2    2022-06-14 12:34:00 -0.000192
3    2022-06-14 12:33:00  0.000096
4    2022-06-14 12:32:00  0.000000
...                  ...       ...
4109 2022-06-09 17:04:00  0.000094
4110 2022-06-09 17:03:00  0.000000
4111 2022-06-09 17:02:00  0.000000
4112 2022-06-09 17:01:00  0.000000
4113 2022-06-09 17:00:00  0.000000

[4114 rows x 2 columns]

In [41]:
### simple CNN

In [38]:
#split train set (use data before June 14 as train set)
window = 5
x_train, y_train = [], []

for i in range(757,4114-5):
    x_train.append(cur_r.loc[i + 1 : i + window, 'return'])
    y_train.append(cur_r.loc[i, 'return'])

#convert the list to ndarray
x_train = np.array(x_train)
y_train = np.array(y_train)

In [49]:
# split test set (use data in June 14 as test set)
x_test, y_test = [], []

for i in range(752):
    x_test.append(cur_r.loc[i + 1 : i + window, 'return'])
    y_test.append(cur_r.loc[i, 'return'])

#convert the list to ndarray
x_test = np.array(x_test)
y_test = np.array(y_test)

In [39]:
x_train

array([[-1.91809725e-04,  0.00000000e+00,  0.00000000e+00,
        -9.58910678e-05,  2.87700793e-04],
       [ 0.00000000e+00,  0.00000000e+00, -9.58910678e-05,
         2.87700793e-04, -9.59094615e-05],
       [ 0.00000000e+00, -9.58910678e-05,  2.87700793e-04,
        -9.59094615e-05,  9.59094615e-05],
       ...,
       [-1.88359390e-04,  9.41752602e-05,  9.41841300e-05,
         0.00000000e+00,  0.00000000e+00],
       [ 9.41752602e-05,  9.41841300e-05,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00],
       [ 9.41841300e-05,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00]])

In [40]:
y_train

array([ 9.59094615e-05, -1.91809725e-04,  0.00000000e+00, ...,
        1.88359390e-04, -1.88359390e-04,  9.41752602e-05])

In [43]:
x_train.shape

(3352, 5)

In [44]:
y_train.shape

(3352,)

In [45]:
# convert x_train to 3D tensor
# x_train[data_index, time_point, channel]
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1], 1))
x_train.shape

(3352, 5, 1)

In [52]:
# convert x_test to 3D tensor
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1], 1))
x_test.shape

(752, 5, 1)

In [80]:
# build a CNN
# 2 convolutional layers and 1 FNN hidden layer
model = tf.keras.models.Sequential()

# First coonvolutional layer
model.add(tf.keras.layers.Conv1D(filters = 4, kernel_size = 2, activation = 'relu', input_shape = (window,1)))# 1 channel only

# Second convolutional layer
model.add(tf.keras.layers.Conv1D(filters = 6, kernel_size = 2, activation = 'relu'))

# Global average pooling to collapse the matrix into a vector
model.add(tf.keras.layers.GlobalAveragePooling1D())

# FNN hidden layer with 8 neurons
model.add(tf.keras.layers.Dense(8, activation = 'relu'))

# Output layer
model.add(tf.keras.layers.Dense(1, activation = 'linear'))

In [81]:
# train the model
model.compile(loss = 'mean_squared_error')
model.fit(x_train, y_train, epochs = 100, verbose = 1)

Epoch 1/100
105/105 [==============================] - 1s 1ms/step - loss: 3.0630e-06
Epoch 2/100
105/105 [==============================] - 0s 1ms/step - loss: 2.3056e-06
Epoch 3/100
105/105 [==============================] - 0s 1ms/step - loss: 1.7858e-06
Epoch 4/100
105/105 [==============================] - 0s 1ms/step - loss: 1.4961e-06
Epoch 5/100
105/105 [==============================] - 0s 1ms/step - loss: 1.3321e-06
Epoch 6/100
105/105 [==============================] - 0s 1ms/step - loss: 1.1221e-06
Epoch 7/100
105/105 [==============================] - 0s 1ms/step - loss: 8.3658e-07
Epoch 8/100
105/105 [==============================] - 0s 1ms/step - loss: 7.7360e-07
Epoch 9/100
105/105 [==============================] - 0s 1ms/step - loss: 7.3627e-07
Epoch 10/100
105/105 [==============================] - 0s 1ms/step - loss: 6.6696e-07
Epoch 11/100
105/105 [==============================] - 0s 1ms/step - loss: 6.3268e-07
Epoch 12/100
105/105 [==============================

105/105 [==============================] - 0s 1ms/step - loss: 2.8489e-07
Epoch 96/100
105/105 [==============================] - 0s 1ms/step - loss: 2.7449e-07
Epoch 97/100
105/105 [==============================] - 0s 1ms/step - loss: 2.7790e-07
Epoch 98/100
105/105 [==============================] - 0s 1ms/step - loss: 2.7464e-07
Epoch 99/100
105/105 [==============================] - 0s 1ms/step - loss: 2.8526e-07
Epoch 100/100
105/105 [==============================] - 0s 1ms/step - loss: 2.6497e-07


In [87]:
# evaluate the model quality (on test set)
cur_r_test = cur_r[:752]
y_pred = model.predict(x_test)
y_pred = y_pred.flatten()
cur_r_test.loc[:,'predicted r'] = y_pred
cur_r_test

24/24 [==============================] - 0s 957us/step


D:\anaconda\lib\site-packages\pandas\core\indexing.py:1596: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[key] = _infer_fill_value(value)
D:\anaconda\lib\site-packages\pandas\core\indexing.py:1745: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  isetter(ilocs[0], value)


Date    return  predicted r
0   2022-06-14 12:36:00 -0.000096     0.000537
1   2022-06-14 12:35:00 -0.000192     0.000537
2   2022-06-14 12:34:00 -0.000192     0.000537
3   2022-06-14 12:33:00  0.000096     0.000537
4   2022-06-14 12:32:00  0.000000     0.000537
..                  ...       ...          ...
747 2022-06-14 00:09:00  0.000000     0.000537
748 2022-06-14 00:08:00  0.000096     0.000537
749 2022-06-14 00:07:00 -0.000096     0.000537
750 2022-06-14 00:06:00 -0.000096     0.000537
751 2022-06-14 00:05:00 -0.000096     0.000537

[752 rows x 3 columns]

In [88]:
### This is a definitely bad model. I think this is because return is too small.
### Try mixture density network!

In [91]:
### Mixture density network
import tensorflow_probability as tfp
tfd = tfp.distributions
tfpl = tfp.layers
tfk = tf.keras
tfkl = tf.keras.layers

In [139]:
# build the model
event_shape = [1]
num_components = 6  # normal mixture with 5 components
params_size = tfp.layers.MixtureNormal.params_size(num_components, event_shape)
model = tfk.Sequential([
    tfkl.Dense(10, activation='relu'),
    tfkl.Dense(12, activation='relu'),
    tfkl.Dense(10, activation='relu'),
    tfkl.Dense(params_size, activation=None),
    tfpl.MixtureNormal(num_components, event_shape)
])

In [158]:
x_train = x_train.reshape((x_train.shape[0], x_train.shape[1]))
x_test = x_test.reshape((x_test.shape[0], x_test.shape[1]))

In [140]:
# fit
model.compile(optimizer="adam",
              loss=lambda y, model: -model.log_prob(y))
model.fit(x_train, y_train, batch_size=64, epochs=200)

Epoch 1/200
53/53 [==============================] - 1s 1ms/step - loss: 0.4924
Epoch 2/200
53/53 [==============================] - 0s 1ms/step - loss: -0.1303
Epoch 3/200
53/53 [==============================] - 0s 1ms/step - loss: -3.0858
Epoch 4/200
53/53 [==============================] - 0s 1ms/step - loss: -4.6219
Epoch 5/200
53/53 [==============================] - 0s 1ms/step - loss: -2.4860
Epoch 6/200
53/53 [==============================] - 0s 1ms/step - loss: -3.1072
Epoch 7/200
53/53 [==============================] - 0s 1ms/step - loss: 2.1814
Epoch 8/200
53/53 [==============================] - 0s 1ms/step - loss: -1.1130
Epoch 9/200
53/53 [==============================] - 0s 1ms/step - loss: -3.2614
Epoch 10/200
53/53 [==============================] - 0s 1ms/step - loss: -4.3953
Epoch 11/200
53/53 [==============================] - 0s 1ms/step - loss: -4.2477
Epoch 12/200
53/53 [==============================] - 0s 1ms/step - loss: -5.0004
Epoch 13/200
53/53 [=======

53/53 [==============================] - 0s 1ms/step - loss: -5.5837
Epoch 102/200
53/53 [==============================] - 0s 1ms/step - loss: -5.7925
Epoch 103/200
53/53 [==============================] - 0s 1ms/step - loss: -4.7543
Epoch 104/200
53/53 [==============================] - 0s 1ms/step - loss: -5.6299
Epoch 105/200
53/53 [==============================] - 0s 1ms/step - loss: -5.8718
Epoch 106/200
53/53 [==============================] - 0s 1ms/step - loss: -3.3032
Epoch 107/200
53/53 [==============================] - 0s 1ms/step - loss: -5.2740
Epoch 108/200
53/53 [==============================] - 0s 1ms/step - loss: -5.4712
Epoch 109/200
53/53 [==============================] - 0s 1ms/step - loss: -5.6579
Epoch 110/200
53/53 [==============================] - 0s 1ms/step - loss: -5.8468
Epoch 111/200
53/53 [==============================] - 0s 1ms/step - loss: -4.0706
Epoch 112/200
53/53 [==============================] - 0s 1ms/step - loss: -5.3991
Epoch 113/200
53/5

53/53 [==============================] - 0s 1ms/step - loss: -4.1482
Epoch 200/200
53/53 [==============================] - 0s 1ms/step - loss: -5.7006


In [161]:
x0 = np.array([[-1.91809725e-04,  0.00000000e+00,  0.00000000e+00,
        -9.58910678e-05,  2.87700793e-04]])
gm = model(x_0)

# get the mixture parameters:
gm_weights = gm.mixture_distribution.probs_parameter().numpy().flatten()
gm_means = gm.components_distribution.mean().numpy().flatten()
gm_vars = gm.components_distribution.variance().numpy().flatten()

print("Component weights: ", gm_weights)
print("Component means: ", gm_means)
print("Component variances: ", gm_vars)

print("Predicted mean: ", np.dot(gm_weights, gm_means))
print("Predicted st dev: ", np.sqrt(np.dot(gm_weights**2, gm_vars)))

Component weights:  [2.8006723e-05 2.3993396e-05 9.6329459e-05 9.9983752e-01 4.4129492e-06
 9.8246019e-06]
Component means:  [ 7.0027262e-02 -1.6629617e-01 -1.0554394e-01 -1.0059774e-04
  2.4806380e-01 -3.8287240e-01]
Component variances:  [2.3707175e-06 6.2863892e-06 6.7535348e-07 1.3783897e-06 1.9540012e-04
 1.7138427e-05]
Predicted mean:  -0.00011544404
Predicted st dev:  0.0011738576


In [172]:
y_pred = model.predict(x_test)

24/24 [==============================] - 0s 957us/step


array([[-6.14521501e-04],
       [-4.95711458e-04],
       [-2.05923780e-03],
       [-1.04239106e-03],
       [-8.50803568e-04],
       [ 2.39538378e-03],
       [-3.71016533e-04],
       [ 1.52787718e-03],
       [-1.83179465e-04],
       [-3.02456203e-04],
       [ 3.43588530e-04],
       [ 2.89986609e-03],
       [ 4.83548676e-04],
       [ 6.03162567e-04],
       [ 1.13323971e-04],
       [-1.32203649e-03],
       [-1.17863878e-04],
       [ 5.48776414e-04],
       [ 5.61767316e-04],
       [ 2.33423576e-04],
       [ 1.28777127e-03],
       [-1.76280551e-03],
       [ 1.32980035e-03],
       [ 2.06183409e-03],
       [ 1.04750751e-03],
       [-2.75446044e-04],
       [ 5.16149230e-05],
       [-1.82567420e-03],
       [ 3.16376041e-04],
       [-8.53540085e-04],
       [ 2.07439065e-04],
       [-2.64385249e-04],
       [-1.16538361e-03],
       [ 1.38207257e-03],
       [ 5.55095612e-04],
       [-4.59167059e-04],
       [-1.10048539e-04],
       [-1.19124365e-03],
       [-2.1

In [173]:
y_test

array([-9.59738952e-05, -1.91938580e-04, -1.91901747e-04,  9.59462702e-05,
        0.00000000e+00, -9.59462702e-05,  0.00000000e+00,  0.00000000e+00,
        2.87866432e-04,  2.87949323e-04,  1.92012289e-04, -9.60107533e-05,
        9.60107533e-05,  9.60199722e-05, -1.92030726e-04, -4.79915544e-04,
        1.91938580e-04,  1.91975428e-04, -1.91975428e-04,  9.59831070e-05,
        3.84024582e-04,  9.60291929e-05,  0.00000000e+00, -9.60291929e-05,
       -2.88032262e-04,  9.60015361e-05,  9.60107533e-05, -2.88004610e-04,
        9.59923207e-05,  9.60015361e-05, -9.60015361e-05,  0.00000000e+00,
        0.00000000e+00,  9.60015361e-05,  1.92030726e-04,  0.00000000e+00,
       -2.88032262e-04,  0.00000000e+00,  3.84061455e-04, -3.84061455e-04,
        9.60015361e-05,  2.88059918e-04,  1.92086055e-04,  1.92122959e-04,
       -1.92122959e-04, -1.92086055e-04,  0.00000000e+00,  1.92086055e-04,
        9.60568657e-05, -4.80192086e-04,  1.92049165e-04,  1.92086055e-04,
       -9.60476397e-05, -

In [175]:
import os
os.getcwd()

'C:\\Users\\lenovo\\Desktop\\COMP0041_Python_review'